# Trabalho da disciplina Projeto/MVP em Engenharia de Dados

## Aluno: Luis Eduardo Ribeiro Veiga - RA: 40520223000855

**Descrição do Problema** - Construir um pipeline de dados utilizando tecnologias na nuvem. O pipeline irá envolver a busca, coleta, modelagem, carga e análise dos dados.

**Objetivo** - O objetivo do trabalho é montar um repositório que permita obter informações sobre taxas de evasão, repetência e promoção de alunos matriculados no ensino fundamental e médio nos vários municípios do Brasil - apesar da taxa de migração para EJA estar presente no repositório, o mesmo não será considerado na avaliação. O período de cobertura compreenderá os anos 2014 até 2019. Para enriquecer a análise serão incluídos na base de avaliação dados referentes ao PIB per-carpita e o repasse do programa Bolsa Família aos municípios.

### Busca pelos dados

Seguem abaixo os conjuntos de dados utilizados no trabalho.

**Dados do Bolsa Família** - https://dados.gov.br/dados/conjuntos-dados/bolsa-familia---mi-social

Esse conjunto de dados informa a quantidade de famílias beneficiárias e o valor repassado através da folha de pagamento do Bolsa Família, assim como o município e ano/mês de referência.

Nesse conjunto de dados temos as seguintes variáveis:

De 2004 a 2021:

ibge : código ibge do município  
anomes : ano e mês de referência  
qtd_familias_beneficiarias_bolsa_familia : Quantidade de famílias beneficiárias do Programa Bolsa Família  
valor_repassado_bolsa_familia : Valor repassado para pagamento de benefícios do Programa Bolsa Família

Licença: Creative Commons Atribuição


**Taxas de Transição** - https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/indicadores-educacionais/taxas-de-transicao

Nesse conjunto de dados temos as seguintes variáveis:

Ano : ano da matrícula / ano da próxima matrícula  
Região : norte, nordeste, centro-oeste, sudeste e sul  
UF : unidade federativa  
Código do município	: código ibge do município  
Nome do município : nome do município  
Localização	: total, urbana, rural  
Dependência Administrativa : total, pública, privada  
Taxa de Promoção - Ensino Fundamental - Total  
Taxa de Promoção - Ensino Fundamental - Anos Iniciais  
Taxa de Promoção - Ensino Fundamental - Anos Finais  
Taxa de Promoção - Ensino Fundamental - 1º Ano  
Taxa de Promoção - Ensino Fundamental - 2º Ano  
Taxa de Promoção - Ensino Fundamental - 3º Ano  
Taxa de Promoção - Ensino Fundamental - 4º Ano  
Taxa de Promoção - Ensino Fundamental - 5º Ano  
Taxa de Promoção - Ensino Fundamental - 6º Ano  
Taxa de Promoção - Ensino Fundamental - 7º Ano  
Taxa de Promoção - Ensino Fundamental - 8º Ano  
Taxa de Promoção - Ensino Fundamental - 9º Ano  
Taxa de Promoção - Ensino Médio - Total  
Taxa de Promoção - Ensino Médio - 1ª série  
Taxa de Promoção - Ensino Médio - 2ª série  
Taxa de Promoção - Ensino Médio - 3ª série  
Taxa de Repetência - Ensino Fundamental - Total  
Taxa de Repetência - Ensino Fundamental - Anos Iniciais  
Taxa de Repetência - Ensino Fundamental - Anos Finais  
Taxa de Repetência - Ensino Fundamental - 1º Ano  
Taxa de Repetência - Ensino Fundamental - 2º Ano  
Taxa de Repetência - Ensino Fundamental - 3º Ano  
Taxa de Repetência - Ensino Fundamental - 4º Ano  
Taxa de Repetência - Ensino Fundamental - 5º Ano  
Taxa de Repetência - Ensino Fundamental - 6º Ano  
Taxa de Repetência - Ensino Fundamental - 7º Ano  
Taxa de Repetência - Ensino Fundamental - 8º Ano  
Taxa de Repetência - Ensino Fundamental - 9º Ano  
Taxa de Repetência - Ensino Médio - Total  
Taxa de Repetência - Ensino Médio - 1ª série  
Taxa de Repetência - Ensino Médio - 2ª série  
Taxa de Repetência - Ensino Médio - 3ª série  
Taxa de Evasão - Ensino Fundamental - Total  
Taxa de Evasão - Ensino Fundamental - Anos Iniciais  
Taxa de Evasão - Ensino Fundamental - Anos Finais  
Taxa de Evasão - Ensino Fundamental - 1º Ano  
Taxa de Evasão - Ensino Fundamental - 2º Ano  
Taxa de Evasão - Ensino Fundamental - 3º Ano  
Taxa de Evasão - Ensino Fundamental - 4º Ano  
Taxa de Evasão - Ensino Fundamental - 5º Ano  
Taxa de Evasão - Ensino Fundamental - 6º Ano  
Taxa de Evasão - Ensino Fundamental - 7º Ano  
Taxa de Evasão - Ensino Fundamental - 8º Ano  
Taxa de Evasão - Ensino Fundamental - 9º Ano  
Taxa de Evasão - Ensino Médio - Total  
Taxa de Evasão - Ensino Médio - 1ª série  
Taxa de Evasão - Ensino Médio - 2ª série  
Taxa de Evasão - Ensino Médio - 3ª série  
Migração para EJA - Ensino Fundamental  
Migração para EJA - Ensino Fundamental - Total  
Migração para EJA - Ensino Fundamental - Anos Iniciais  
Migração para EJA - Ensino Fundamental - Anos Finais  
Migração para EJA - Ensino Fundamental - 1º Ano  
Migração para EJA - Ensino Fundamental - 2º Ano  
Migração para EJA - Ensino Fundamental - 3º Ano  
Migração para EJA - Ensino Fundamental - 4º Ano  
Migração para EJA - Ensino Fundamental - 5º Ano  
Migração para EJA - Ensino Fundamental - 6º Ano  
Migração para EJA - Ensino Fundamental - 7º Ano  
Migração para EJA - Ensino Fundamental - 8º Ano  
Migração para EJA - Ensino Fundamental - 9º Ano  
Migração para EJA - Ensino Médio - Total  
Migração para EJA - Ensino Médio - 1ª série  
Migração para EJA - Ensino Médio - 2ª série  
Migração para EJA - Ensino Médio - 3ª série  

**Produto Interno Bruto per capita** - https://dados.gov.br/dados/conjuntos-dados/cgeo_vw_pib_percapita

O Produto Interno Bruto - PIB per capita de cada município foi estimado pelo quociente entre o valor do PIB do municípioe sua população residente. Para a população, foi utilizada a estimativa encaminhada pelo IBGE ao Tribunal de Contas da União- TCU, em outubro de 2009, tendo 1º de julho de 2009 como data de referência.Produto interno bruto é o total dos bens e serviços produzidos pelas unidades produtoras residentes destinados ao consumofinal sendo, portanto, equivalente à soma dos valores adicionados pelas diversas atividades econômicas acrescida dos impostos,líquidos de subsídios, sobre produtos. O produto interno bruto também é equivalente à soma dos consumos finais de bense serviços valorados a preço de mercado sendo, também, equivalente à soma das rendas primárias.

Nesse conjunto de dados temos as seguintes variáveis:

FID  
gid  
UF  
nome  
Censo  
PIB  
Pop_est_2009  
PIB_percapita  
Descrição  
legenda  
classe  
geom  

Licença: License not specified

**DTB - Divisão Territorial Brasileira** - https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/23701-divisao-territorial-brasileira.html?=&t=downloads

Apresenta a relação de subdistritos, distritos e municípios que compõem, a cada ano, a divisão territorial brasileira oficial. Os arquivos trazem igualmente os geocódigos e a hierarquia administrativa às quais essas unidades estão subordinadas.

Nesse conjunto de dados temos as seguintes variáveis:

UF  
Nome_UF  
Região Geográfica Intermediária  
Nome Região Geográfica Intermediária  
Região Geográfica Imediata  
Nome Região Geográfica Imediata  
Mesorregião Geográfica  
Nome_Mesorregião  
Microrregião Geográfica  
Nome_Microrregião  
Município  
Código Município Completo  
Nome_Município

### Coleta

### Modelagem

### Carga

In [3]:
bucket_path = "gs://mvp-sprint-eng-dados-bucket/"
big_query_dataset = "mvp-sprint-eng-dados-project.mvp_sprint_eng_dados_bq_dataset"

In [4]:
bolsa_familia_2014_path = bucket_path + "bolsa_familia_2014.txt"
bolsa_familia_2015_path = bucket_path + "bolsa_familia_2015.txt"
bolsa_familia_2016_path = bucket_path + "bolsa_familia_2016.txt"
bolsa_familia_2017_path = bucket_path + "bolsa_familia_2017.txt"
bolsa_familia_2018_path = bucket_path + "bolsa_familia_2018.txt"
bolsa_familia_2019_path = bucket_path + "bolsa_familia_2019.txt"

In [5]:
bolsa_familia_2014_2019_df = spark.read.option("inferSchema",True).option("header",True).csv(bolsa_familia_2014_path)
bolsa_familia_2014_2019_df = bolsa_familia_2014_2019_df.union(spark.read.option("inferSchema",True).option("header",True).csv(bolsa_familia_2015_path))
bolsa_familia_2014_2019_df = bolsa_familia_2014_2019_df.union(spark.read.option("inferSchema",True).option("header",True).csv(bolsa_familia_2016_path))
bolsa_familia_2014_2019_df = bolsa_familia_2014_2019_df.union(spark.read.option("inferSchema",True).option("header",True).csv(bolsa_familia_2017_path))
bolsa_familia_2014_2019_df = bolsa_familia_2014_2019_df.union(spark.read.option("inferSchema",True).option("header",True).csv(bolsa_familia_2018_path))
bolsa_familia_2014_2019_df = bolsa_familia_2014_2019_df.union(spark.read.option("inferSchema",True).option("header",True).csv(bolsa_familia_2019_path))

In [6]:
bolsa_familia_2014_2019_df = bolsa_familia_2014_2019_df.withColumn("valor_medio_beneficio", bolsa_familia_2014_2019_df.valor_repassado_bolsa_familia / bolsa_familia_2014_2019_df.qtd_familias_beneficiarias_bolsa_familia)
bolsa_familia_2014_2019_df = bolsa_familia_2014_2019_df.withColumn("ano", bolsa_familia_2014_2019_df.anomes.substr( 1, 4).cast("int"))
bolsa_familia_2014_2019_df = bolsa_familia_2014_2019_df.withColumn("mes", bolsa_familia_2014_2019_df.anomes.substr( 5, 2).cast("int"))
bolsa_familia_2014_2019_df = bolsa_familia_2014_2019_df.withColumnRenamed("ibge","codigo_regiao")
bolsa_familia_2014_2019_df = bolsa_familia_2014_2019_df.drop("anomes")

In [7]:
spark.sql("DROP TABLE IF EXISTS bolsa_familia_2014_2019_table")
bolsa_familia_2014_2019_df.write.saveAsTable("bolsa_familia_2014_2019_table")

ivysettings.xml file not found in HIVE_HOME or HIVE_CONF_DIR,/etc/hive/conf.dist/ivysettings.xml will be used
23/09/10 04:48:46 WARN SessionState: METASTORE_FILTER_HOOK will be ignored, since hive.security.authorization.manager is set to instance of HiveAuthorizerFactory.

In [8]:
bolsa_familia_2014_2019_df = spark.sql('''
    select codigo_regiao, ano, sum(qtd_familias_beneficiarias_bolsa_familia)/count(qtd_familias_beneficiarias_bolsa_familia) media_qtd_familias_beneficiarias_bolsa_familia, sum(valor_repassado_bolsa_familia)/count(valor_repassado_bolsa_familia) media_valor_repassado_bolsa_familia, sum(valor_medio_beneficio)/count(valor_medio_beneficio) media_valor_medio_beneficio from bolsa_familia_2014_2019_table group by codigo_regiao, ano
    ''')

In [9]:
bolsa_familia_2014_2019_df.printSchema()

root
 |-- codigo_regiao: integer (nullable = true)
 |-- ano: integer (nullable = true)
 |-- media_qtd_familias_beneficiarias_bolsa_familia: double (nullable = true)
 |-- media_valor_repassado_bolsa_familia: double (nullable = true)
 |-- media_valor_medio_beneficio: double (nullable = true)

In [10]:
pib_municipios_2010_2020_path = bucket_path + "pib_municipios_2010_2020.csv"

In [11]:
pib_municipios_2010_2020_df = spark.read.option("inferSchema",True).option("header",True).option("delimiter",";").csv(pib_municipios_2010_2020_path)

In [12]:
pib_municipios_2010_2020_df = pib_municipios_2010_2020_df.drop("Código da Grande Região","Nome da Grande Região","Código da Unidade da Federação",
                                                               "Sigla da Unidade da Federação","Nome da Unidade da Federação",
                                                               "Região Metropolitana","Código da Mesorregião","Nome da Mesorregião",
                                                               "Código da Microrregião","Nome da Microrregião",
                                                               "Município da Região Geográfica Imediata","Código da Região Geográfica Intermediária",
                                                               "Nome da Região Geográfica Intermediária","Município da Região Geográfica Intermediária",
                                                               "Código Concentração Urbana","Nome Concentração Urbana","Tipo Concentração Urbana",
                                                               "Código Arranjo Populacional","Nome Arranjo Populacional","Hierarquia Urbana",
                                                               "Hierarquia Urbana (principais categorias)","Código da Região Rural","Nome da Região Rural",
                                                               "Região rural (segundo classificação do núcleo)","Amazônia Legal","Semiárido",
                                                               "Cidade-Região de São Paulo","Valor adicionado bruto da Agropecuária, a preços correntes(R$ 1.000)",
                                                               "Valor adicionado bruto da Indústria,a preços correntes(R$ 1.000)",
                                                               "Valor adicionado bruto dos Serviços,a preços correntes - exceto Administração, defesa, educação e saúde públicas e seguridade social(R$ 1.000)",
                                                               "Valor adicionado bruto da Administração, defesa, educação e saúde públicas e seguridade social, a preços correntes(R$ 1.000)",
                                                               "Valor adicionado bruto total, a preços correntes(R$ 1.000)",
                                                               "Impostos, líquidos de subsídios, sobre produtos, a preços correntes(R$ 1.000)",
                                                               "Atividade com maior valor adicionado bruto","Atividade com segundo maior valor adicionado bruto",
                                                               "Atividade com terceiro maior valor adicionado bruto","Nome do Município",
                                                               "Nome da Região Geográfica Imediata")

In [13]:
pib_municipios_2010_2020_df = pib_municipios_2010_2020_df.withColumnRenamed("Ano","ano").withColumnRenamed("Código do Município","codigo_municipio").withColumnRenamed("Código da Região Geográfica Imediata","codigo_regiao").withColumnRenamed("Produto Interno Bruto, a preços correntes(R$ 1.000)","pib").withColumnRenamed("Produto Interno Bruto per capita, a preços correntes(R$ 1,00)","pib_percapita")

In [14]:
pib_municipios_2010_2020_df.printSchema()

root
 |-- ano: integer (nullable = true)
 |-- codigo_municipio: integer (nullable = true)
 |-- codigo_regiao: integer (nullable = true)
 |-- pib: string (nullable = true)
 |-- pib_percapita: string (nullable = true)

In [15]:
relatorio_dtb_brasil_municipio_path = bucket_path + "relatorio_dtb_brasil_municipio.csv"

In [16]:
relatorio_dtb_brasil_municipio_df = spark.read.option("inferSchema",True).option("header",True).option("delimiter",";").csv(relatorio_dtb_brasil_municipio_path)

In [17]:
relatorio_dtb_brasil_municipio_df = relatorio_dtb_brasil_municipio_df.drop("Região Geográfica Intermediária","Nome Região Geográfica Intermediária",
                                                                           "Mesorregião Geográfica","Nome_Mesorregião","Microrregião Geográfica",
                                                                           "Nome_Microrregião","Município","_c13","_c14","_c15","_c16","_c17","_c18")

In [18]:
relatorio_dtb_brasil_municipio_df = relatorio_dtb_brasil_municipio_df.withColumnRenamed("UF","uf").withColumnRenamed("Nome_UF","nome_uf").withColumnRenamed("Região Geográfica Imediata","codigo_regiao").withColumnRenamed("Nome Região Geográfica Imediata","nome_regiao").withColumnRenamed("Código Município Completo","codigo_municipio").withColumnRenamed("Nome_Município","nome_municipio")

In [19]:
relatorio_dtb_brasil_municipio_df.printSchema()

root
 |-- uf: integer (nullable = true)
 |-- nome_uf: string (nullable = true)
 |-- codigo_regiao: integer (nullable = true)
 |-- nome_regiao: string (nullable = true)
 |-- codigo_municipio: integer (nullable = true)
 |-- nome_municipio: string (nullable = true)

In [20]:
tx_transicao_municipios_2014_2015_path = bucket_path + "tx_transicao_municipios_2014_2015.csv"
tx_transicao_municipios_2015_2016_path = bucket_path + "tx_transicao_municipios_2015_2016.csv"
tx_transicao_municipios_2016_2017_path = bucket_path + "tx_transicao_municipios_2016_2017.csv"
tx_transicao_municipios_2017_2018_path = bucket_path + "tx_transicao_municipios_2017_2018.csv"
tx_transicao_municipios_2018_2019_path = bucket_path + "tx_transicao_municipios_2018_2019.csv"
tx_transicao_municipios_2019_2020_path = bucket_path + "tx_transicao_municipios_2019_2020.csv"

In [21]:
tx_transicao_municipios_2014_2019_df = spark.read.option("inferSchema",True).option("header",True).option("delimiter",";").csv(tx_transicao_municipios_2014_2015_path)
tx_transicao_municipios_2014_2019_df = tx_transicao_municipios_2014_2019_df.union(spark.read.option("inferSchema",True).option("header",True).option("delimiter",";").csv(tx_transicao_municipios_2015_2016_path))
tx_transicao_municipios_2014_2019_df = tx_transicao_municipios_2014_2019_df.union(spark.read.option("inferSchema",True).option("header",True).option("delimiter",";").csv(tx_transicao_municipios_2016_2017_path))
tx_transicao_municipios_2014_2019_df = tx_transicao_municipios_2014_2019_df.union(spark.read.option("inferSchema",True).option("header",True).option("delimiter",";").csv(tx_transicao_municipios_2017_2018_path))
tx_transicao_municipios_2014_2019_df = tx_transicao_municipios_2014_2019_df.union(spark.read.option("inferSchema",True).option("header",True).option("delimiter",";").csv(tx_transicao_municipios_2018_2019_path))
tx_transicao_municipios_2014_2019_df = tx_transicao_municipios_2014_2019_df.union(spark.read.option("inferSchema",True).option("header",True).option("delimiter",";").csv(tx_transicao_municipios_2019_2020_path))

In [22]:
spark.sql("DROP TABLE IF EXISTS tx_transicao_municipios_2014_2019_table")
tx_transicao_municipios_2014_2019_df.write.saveAsTable("tx_transicao_municipios_2014_2019_table")

23/09/10 04:48:55 WARN package: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

In [23]:
tx_transicao_municipios_2014_2019_df = spark.sql('''
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXPRO_FUN,',','.') as decimal(5,2)) as valor,'TXPRO_FUN' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXPRO_F14,',','.') as decimal(5,2)) as valor,'TXPRO_F14' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXPRO_F58,',','.') as decimal(5,2)) as valor,'TXPRO_F58' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXPRO_F00,',','.') as decimal(5,2)) as valor,'TXPRO_F00' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXPRO_F01,',','.') as decimal(5,2)) as valor,'TXPRO_F01' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXPRO_F02,',','.') as decimal(5,2)) as valor,'TXPRO_F02' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXPRO_F03,',','.') as decimal(5,2)) as valor,'TXPRO_F03' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXPRO_F04,',','.') as decimal(5,2)) as valor,'TXPRO_F04' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXPRO_F05,',','.') as decimal(5,2)) as valor,'TXPRO_F05' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXPRO_F06,',','.') as decimal(5,2)) as valor,'TXPRO_F06' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXPRO_F07,',','.') as decimal(5,2)) as valor,'TXPRO_F07' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXPRO_F08,',','.') as decimal(5,2)) as valor,'TXPRO_F08' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXPRO_MED,',','.') as decimal(5,2)) as valor,'TXPRO_MED' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXPRO_M01,',','.') as decimal(5,2)) as valor,'TXPRO_M01' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXPRO_M02,',','.') as decimal(5,2)) as valor,'TXPRO_M02' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXPRO_M03,',','.') as decimal(5,2)) as valor,'TXPRO_M03' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXREP_FUN,',','.') as decimal(5,2)) as valor,'TXREP_FUN' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXREP_F14,',','.') as decimal(5,2)) as valor,'TXREP_F14' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXREP_F58,',','.') as decimal(5,2)) as valor,'TXREP_F58' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXREP_F00,',','.') as decimal(5,2)) as valor,'TXREP_F00' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXREP_F01,',','.') as decimal(5,2)) as valor,'TXREP_F01' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXREP_F02,',','.') as decimal(5,2)) as valor,'TXREP_F02' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXREP_F03,',','.') as decimal(5,2)) as valor,'TXREP_F03' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXREP_F04,',','.') as decimal(5,2)) as valor,'TXREP_F04' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXREP_F05,',','.') as decimal(5,2)) as valor,'TXREP_F05' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXREP_F06,',','.') as decimal(5,2)) as valor,'TXREP_F06' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXREP_F07,',','.') as decimal(5,2)) as valor,'TXREP_F07' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXREP_F08,',','.') as decimal(5,2)) as valor,'TXREP_F08' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXREP_MED,',','.') as decimal(5,2)) as valor,'TXREP_MED' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXREP_M01,',','.') as decimal(5,2)) as valor,'TXREP_M01' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXREP_M02,',','.') as decimal(5,2)) as valor,'TXREP_M02' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXREP_M03,',','.') as decimal(5,2)) as valor,'TXREP_M03' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVE_FUN,',','.') as decimal(5,2)) as valor,'TXEVE_FUN' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVE_F14,',','.') as decimal(5,2)) as valor,'TXEVE_F14' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVE_F58,',','.') as decimal(5,2)) as valor,'TXEVE_F58' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVE_F00,',','.') as decimal(5,2)) as valor,'TXEVE_F00' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVE_F01,',','.') as decimal(5,2)) as valor,'TXEVE_F01' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVE_F02,',','.') as decimal(5,2)) as valor,'TXEVE_F02' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVE_F03,',','.') as decimal(5,2)) as valor,'TXEVE_F03' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVE_F04,',','.') as decimal(5,2)) as valor,'TXEVE_F04' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVE_F05,',','.') as decimal(5,2)) as valor,'TXEVE_F05' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVE_F06,',','.') as decimal(5,2)) as valor,'TXEVE_F06' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVE_F07,',','.') as decimal(5,2)) as valor,'TXEVE_F07' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVE_F08,',','.') as decimal(5,2)) as valor,'TXEVE_F08' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVE_MED,',','.') as decimal(5,2)) as valor,'TXEVE_MED' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVE_M01,',','.') as decimal(5,2)) as valor,'TXEVE_M01' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVE_M02,',','.') as decimal(5,2)) as valor,'TXEVE_M02' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVE_M03,',','.') as decimal(5,2)) as valor,'TXEVE_M03' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVM_FUN,',','.') as decimal(5,2)) as valor,'TXEVM_FUN' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVM_F14,',','.') as decimal(5,2)) as valor,'TXEVM_F14' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVM_F58,',','.') as decimal(5,2)) as valor,'TXEVM_F58' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVM_F00,',','.') as decimal(5,2)) as valor,'TXEVM_F00' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVM_F01,',','.') as decimal(5,2)) as valor,'TXEVM_F01' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVM_F02,',','.') as decimal(5,2)) as valor,'TXEVM_F02' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVM_F03,',','.') as decimal(5,2)) as valor,'TXEVM_F03' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVM_F04,',','.') as decimal(5,2)) as valor,'TXEVM_F04' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVM_F05,',','.') as decimal(5,2)) as valor,'TXEVM_F05' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVM_F06,',','.') as decimal(5,2)) as valor,'TXEVM_F06' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVM_F07,',','.') as decimal(5,2)) as valor,'TXEVM_F07' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVM_F08,',','.') as decimal(5,2)) as valor,'TXEVM_F08' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVM_MED,',','.') as decimal(5,2)) as valor,'TXEVM_MED' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVM_M01,',','.') as decimal(5,2)) as valor,'TXEVM_M01' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVM_M02,',','.') as decimal(5,2)) as valor,'TXEVM_M02' as tipo from tx_transicao_municipios_2014_2019_table union
    select cast(substring(ANO,1,4) as int) as ano,CO_MUNICIPIO as codigo_municipio,TIPOLOCA as tipo_local,DEPENDAD as dependencia,cast(replace(TXEVM_M03,',','.') as decimal(5,2)) as valor,'TXEVM_M03' as tipo from tx_transicao_municipios_2014_2019_table
    ''')

In [24]:
tx_transicao_municipios_2014_2019_df.printSchema()

root
 |-- ano: integer (nullable = true)
 |-- codigo_municipio: integer (nullable = true)
 |-- tipo_local: string (nullable = true)
 |-- dependencia: string (nullable = true)
 |-- valor: decimal(5,2) (nullable = true)
 |-- tipo: string (nullable = false)

In [25]:
tx_transicao_municipios_tipo = [
        ("TXPRO_FUN","Taxa de Promoção - Ensino Fundamental - Total"),
        ("TXPRO_F14","Taxa de Promoção - Ensino Fundamental - Anos Iniciais"),
        ("TXPRO_F58","Taxa de Promoção - Ensino Fundamental - Anos Finais"),
        ("TXPRO_F00","Taxa de Promoção - Ensino Fundamental - 1º Ano"),
        ("TXPRO_F01","Taxa de Promoção - Ensino Fundamental - 2º Ano"),
        ("TXPRO_F02","Taxa de Promoção - Ensino Fundamental - 3º Ano"),
        ("TXPRO_F03","Taxa de Promoção - Ensino Fundamental - 4º Ano"),
        ("TXPRO_F04","Taxa de Promoção - Ensino Fundamental - 5º Ano"),
        ("TXPRO_F05","Taxa de Promoção - Ensino Fundamental - 6º Ano"),
        ("TXPRO_F06","Taxa de Promoção - Ensino Fundamental - 7º Ano"),
        ("TXPRO_F07","Taxa de Promoção - Ensino Fundamental - 8º Ano"),
        ("TXPRO_F08","Taxa de Promoção - Ensino Fundamental - 9º Ano"),
        ("TXPRO_MED","Taxa de Promoção -  Ensino Médio - Total"),
        ("TXPRO_M01","Taxa de Promoção -  Ensino Médio - 1ª série"),
        ("TXPRO_M02","Taxa de Promoção -  Ensino Médio - 2ª série"),
        ("TXPRO_M03","Taxa de Promoção -  Ensino Médio - 3ª série"),
        ("TXREP_FUN","Taxa de Repetência - Ensino Fundamental - Total"),
        ("TXREP_F14","Taxa de Repetência - Ensino Fundamental - Anos Iniciais"),
        ("TXREP_F58","Taxa de Repetência - Ensino Fundamental - Anos Finais"),
        ("TXREP_F00","Taxa de Repetência - Ensino Fundamental - 1º Ano"),
        ("TXREP_F01","Taxa de Repetência - Ensino Fundamental - 2º Ano"),
        ("TXREP_F02","Taxa de Repetência - Ensino Fundamental - 3º Ano"),
        ("TXREP_F03","Taxa de Repetência - Ensino Fundamental - 4º Ano"),
        ("TXREP_F04","Taxa de Repetência - Ensino Fundamental - 5º Ano"),
        ("TXREP_F05","Taxa de Repetência - Ensino Fundamental - 6º Ano"),
        ("TXREP_F06","Taxa de Repetência - Ensino Fundamental - 7º Ano"),
        ("TXREP_F07","Taxa de Repetência - Ensino Fundamental - 8º Ano"),
        ("TXREP_F08","Taxa de Repetência - Ensino Fundamental - 9º Ano"),
        ("TXREP_MED","Taxa de Repetência -  Ensino Médio - Total"),
        ("TXREP_M01","Taxa de Repetência -  Ensino Médio - 1ª série"),
        ("TXREP_M02","Taxa de Repetência -  Ensino Médio - 2ª série"),
        ("TXREP_M03","Taxa de Repetência -  Ensino Médio - 3ª série"),
        ("TXEVE_FUN","Taxa de Evasão - Ensino Fundamental - Total"),
        ("TXEVE_F14","Taxa de Evasão - Ensino Fundamental - Anos Iniciais"),
        ("TXEVE_F58","Taxa de Evasão - Ensino Fundamental - Anos Finais"),
        ("TXEVE_F00","Taxa de Evasão - Ensino Fundamental - 1º Ano"),
        ("TXEVE_F01","Taxa de Evasão - Ensino Fundamental - 2º Ano"),
        ("TXEVE_F02","Taxa de Evasão - Ensino Fundamental - 3º Ano"),
        ("TXEVE_F03","Taxa de Evasão - Ensino Fundamental - 4º Ano"),
        ("TXEVE_F04","Taxa de Evasão - Ensino Fundamental - 5º Ano"),
        ("TXEVE_F05","Taxa de Evasão - Ensino Fundamental - 6º Ano"),
        ("TXEVE_F06","Taxa de Evasão - Ensino Fundamental - 7º Ano"),
        ("TXEVE_F07","Taxa de Evasão - Ensino Fundamental - 8º Ano"),
        ("TXEVE_F08","Taxa de Evasão - Ensino Fundamental - 9º Ano"),
        ("TXEVE_MED","Taxa de Evasão -  Ensino Médio - Total"),
        ("TXEVE_M01","Taxa de Evasão -  Ensino Médio - 1ª série"),
        ("TXEVE_M02","Taxa de Evasão -  Ensino Médio - 2ª série"),
        ("TXEVE_M03","Taxa de Evasão -  Ensino Médio - 3ª série"),
        ("TXEVM_FUN","Migração para EJA - Ensino Fundamental - Total"),
        ("TXEVM_F14","Migração para EJA - Ensino Fundamental - Anos Iniciais"),
        ("TXEVM_F58","Migração para EJA - Ensino Fundamental - Anos Finais"),
        ("TXEVM_F00","Migração para EJA - Ensino Fundamental - 1º Ano"),
        ("TXEVM_F01","Migração para EJA - Ensino Fundamental - 2º Ano"),
        ("TXEVM_F02","Migração para EJA - Ensino Fundamental - 3º Ano"),
        ("TXEVM_F03","Migração para EJA - Ensino Fundamental - 4º Ano"),
        ("TXEVM_F04","Migração para EJA - Ensino Fundamental - 5º Ano"),
        ("TXEVM_F05","Migração para EJA - Ensino Fundamental - 6º Ano"),
        ("TXEVM_F06","Migração para EJA - Ensino Fundamental - 7º Ano"),
        ("TXEVM_F07","Migração para EJA - Ensino Fundamental - 8º Ano"),
        ("TXEVM_F08","Migração para EJA - Ensino Fundamental - 9º Ano"),
        ("TXEVM_MED","Migração para EJA -  Ensino Médio - Total"),
        ("TXEVM_M01","Migração para EJA -  Ensino Médio - 1ª série"),
        ("TXEVM_M02","Migração para EJA -  Ensino Médio - 2ª série"),
        ("TXEVM_M03","Migração para EJA -  Ensino Médio - 3ª série")]

In [26]:
tx_transicao_municipios_tipo_df = spark.createDataFrame(data=tx_transicao_municipios_tipo).withColumnRenamed("_1","tipo").withColumnRenamed("_2","descricao")

In [27]:
tx_transicao_municipios_tipo_df.printSchema()

root
 |-- tipo: string (nullable = true)
 |-- descricao: string (nullable = true)

In [28]:
spark.conf.set('temporaryGcsBucket', 'mvp-sprint-eng-dados-bucket')

In [29]:
from google.cloud import bigquery
client_bq = bigquery.Client()

In [30]:
client_bq.delete_table(f'mvp-sprint-eng-dados-project.mvp_sprint_eng_dados_bq_dataset.tx_transicao_municipios_tipo_table', not_found_ok=True)

In [31]:
tx_transicao_municipios_tipo_df.write.format('bigquery') \
    .option('table', f'mvp-sprint-eng-dados-project.mvp_sprint_eng_dados_bq_dataset.tx_transicao_municipios_tipo_table') \
    .mode('append') \
    .save()

In [32]:
client_bq.delete_table(f'mvp-sprint-eng-dados-project.mvp_sprint_eng_dados_bq_dataset.tx_transicao_municipios_2014_2019_table', not_found_ok=True)

In [33]:
tx_transicao_municipios_2014_2019_df.write.format('bigquery') \
    .option('table', f'mvp-sprint-eng-dados-project.mvp_sprint_eng_dados_bq_dataset.tx_transicao_municipios_2014_2019_table') \
    .mode('append') \
    .save()

In [34]:
client_bq.delete_table(f'mvp-sprint-eng-dados-project.mvp_sprint_eng_dados_bq_dataset.relatorio_dtb_brasil_municipio_table', not_found_ok=True)

In [35]:
relatorio_dtb_brasil_municipio_df.write.format('bigquery') \
    .option('table', f'mvp-sprint-eng-dados-project.mvp_sprint_eng_dados_bq_dataset.relatorio_dtb_brasil_municipio_table') \
    .mode('append') \
    .save()

In [36]:
client_bq.delete_table(f'mvp-sprint-eng-dados-project.mvp_sprint_eng_dados_bq_dataset.pib_municipios_2010_2020_table', not_found_ok=True)

In [37]:
pib_municipios_2010_2020_df.write.format('bigquery') \
    .option('table', f'mvp-sprint-eng-dados-project.mvp_sprint_eng_dados_bq_dataset.pib_municipios_2010_2020_table') \
    .mode('append') \
    .save()

In [38]:
client_bq.delete_table(f'mvp-sprint-eng-dados-project.mvp_sprint_eng_dados_bq_dataset.bolsa_familia_2014_2019_table', not_found_ok=True)

In [39]:
bolsa_familia_2014_2019_df.write.format('bigquery') \
    .option('table', f'mvp-sprint-eng-dados-project.mvp_sprint_eng_dados_bq_dataset.bolsa_familia_2014_2019_table') \
    .mode('append') \
    .save()

### Análise

#### Qualidade dos dados

#### Solução do problema